# Generated by Django 3.0.6 on 2020-05-18 16:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('preference', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=1000)),
            ],
            options={
                'ordering': ('number',),
            },
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='book.Chapter')),
                ('edition', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pages', to='preference.Edition')),
            ],
        ),
        migrations.CreateModel(
            name='Term',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000)),
                ('original', models.CharField(blank=True, max_length=1000, null=True)),
                ('page', models.ManyToManyField(to='book.Page')),
            ],
        ),
    ]
