export * from './terms-list.connector';
export * from './terms-list.connector.hook';

const user1 = {
  id: '93c166f3-1b20-4b3f-8624-7188a22b8495',
  firstName: 'Elvis',
  lastName: 'Tang',
  email: 'elvis.tang@gmail.com',
};

export const termsMocks = [
  { id: 1, title: 'Tango', author: user1 },
  { id: 2, title: 'Kilo', author: user1 },
  { id: 3, title: 'X-ray', author: user1 },
  { id: 4, title: 'Yankee', author: user1 },
  { id: 5, title: 'Alfa', author: user1 },
  { id: 6, title: 'Hotel', author: user1 },
  { id: 7, title: 'Papa', author: user1 },
  { id: 8, title: 'Alfa', author: user1 },
  { id: 9, title: 'X-ray', author: user1 },
  { id: 10, title: 'Kilo', author: user1 },
  { id: 11, title: 'Zulu', author: user1 },
  { id: 12, title: 'Uniform', author: user1 },
  { id: 13, title: 'Mike', author: user1 },
  { id: 14, title: 'Victor', author: user1 },
  { id: 15, title: 'Papa', author: user1 },
  { id: 16, title: 'Romeo', author: user1 },
  { id: 17, title: 'Uniform', author: user1 },
  { id: 18, title: 'Zulu', author: user1 },
  { id: 19, title: 'Whiskey', author: user1 },
  { id: 20, title: 'Zulu', author: user1 },
  { id: 21, title: 'Echo', author: user1 },
  { id: 22, title: 'Kilo', author: user1 },
  { id: 23, title: 'Sierra', author: user1 },
  { id: 24, title: 'X-ray', author: user1 },
  { id: 25, title: 'Romeo', author: user1 },
  { id: 26, title: 'Kilo', author: user1 },
  { id: 27, title: 'Sierra', author: user1 },
  { id: 28, title: 'Zulu', author: user1 },
  { id: 29, title: 'Hotel', author: user1 },
  { id: 30, title: 'Zulu', author: user1 },
  { id: 31, title: 'Oscar', author: user1 },
  { id: 32, title: 'Quebec', author: user1 },
  { id: 33, title: 'Alfa', author: user1 },
  { id: 34, title: 'Zulu', author: user1 },
  { id: 35, title: 'Sierra', author: user1 },
  { id: 36, title: 'Bravo', author: user1 },
  { id: 37, title: 'Sierra', author: user1 },
  { id: 38, title: 'Zulu', author: user1 },
  { id: 39, title: 'Sierra', author: user1 },
  { id: 40, title: 'Lima', author: user1 },
  { id: 41, title: 'Alfa', author: user1 },
  { id: 42, title: 'Quebec', author: user1 },
  { id: 43, title: 'X-ray', author: user1 },
  { id: 44, title: 'Charlie', author: user1 },
  { id: 45, title: 'Echo', author: user1 },
  { id: 46, title: 'Juliett', author: user1 },
  { id: 47, title: 'Delta', author: user1 },
  { id: 48, title: 'Yankee', author: user1 },
  { id: 49, title: 'Victor', author: user1 },
  { id: 50, title: 'Papa', author: user1 },
  { id: 51, title: 'Lima', author: user1 },
  { id: 52, title: 'Lima', author: user1 },
  { id: 53, title: 'Lima', author: user1 },
  { id: 54, title: 'Charlie', author: user1 },
  { id: 55, title: 'Delta', author: user1 },
  { id: 56, title: 'India', author: user1 },
  { id: 57, title: 'Foxtrot', author: user1 },
  { id: 58, title: 'November', author: user1 },
  { id: 59, title: 'Oscar', author: user1 },
  { id: 60, title: 'Lima', author: user1 },
  { id: 61, title: 'November', author: user1 },
  { id: 62, title: 'Juliett', author: user1 },
  { id: 63, title: 'Uniform', author: user1 },
  { id: 64, title: 'Whiskey', author: user1 },
  { id: 65, title: 'Sierra', author: user1 },
  { id: 66, title: 'Mike', author: user1 },
  { id: 67, title: 'Sierra', author: user1 },
  { id: 68, title: 'Papa', author: user1 },
  { id: 69, title: 'Kilo', author: user1 },
  { id: 70, title: 'Juliett', author: user1 },
  { id: 71, title: 'Oscar', author: user1 },
  { id: 72, title: 'Sierra', author: user1 },
  { id: 73, title: 'Charlie', author: user1 },
  { id: 74, title: 'Charlie', author: user1 },
  { id: 75, title: 'Papa', author: user1 },
  { id: 76, title: 'Foxtrot', author: user1 },
  { id: 77, title: 'Foxtrot', author: user1 },
  { id: 78, title: 'Mike', author: user1 },
  { id: 79, title: 'November', author: user1 },
  { id: 80, title: 'Golf', author: user1 },
  { id: 81, title: 'Foxtrot', author: user1 },
  { id: 82, title: 'Sierra', author: user1 },
  { id: 83, title: 'Papa', author: user1 },
  { id: 84, title: 'India', author: user1 },
  { id: 85, title: 'Whiskey', author: user1 },
  { id: 86, title: 'X-ray', author: user1 },
  { id: 87, title: 'X-ray', author: user1 },
  { id: 88, title: 'Uniform', author: user1 },
  { id: 89, title: 'Tango', author: user1 },
  { id: 90, title: 'Charlie', author: user1 },
  { id: 91, title: 'Quebec', author: user1 },
  { id: 92, title: 'Charlie', author: user1 },
  { id: 93, title: 'Delta', author: user1 },
  { id: 94, title: 'Victor', author: user1 },
  { id: 95, title: 'Bravo', author: user1 },
  { id: 96, title: 'Whiskey', author: user1 },
  { id: 97, title: 'Charlie', author: user1 },
  { id: 98, title: 'Hotel', author: user1 },
  { id: 99, title: 'India', author: user1 },
  { id: 100, title: 'Zulu', author: user1 },
];
