service: beelzebub

provider:
  name: aws
  profile: personal
  runtime: nodejs12.x

plugins:
  - serverless-webpack
  - serverless-offline

custom:
  serverless-offline:
    port: 4000
  webpack:
    webpackConfig: 'webpack.config.js' # Name of webpack configuration file
    includeModules: false # Node modules configuration for packaging
    packager: 'yarn' # Packager that will be used to package your external modules
    excludeFiles: src/**/*.test.js # Provide a glob for files to ignore

functions:
  hello:
    handler: src/index.handlerPT
    events:
      - http: GET hello
  graphql:
    handler: src/index.handler
    events:
      - http:
          method: any
          path: graphql
