service: hello-world

provider:
  name: aws
  profile: personal
  runtime: nodejs8.10
  stage: dev

plugins:
  - serverless-plugin-typescript
  - serverless-offline

custom:
  serverless-offline:
    port: 4000

functions:
  hello:
    handler: src/hello.handler
    events:
      - http: GET hello
  graphql:
    handler: src/index.handler
    events:
      - http:
          method: any
          path: graphql
