service: beelzebub

provider:
  name: aws
  profile: personal
  runtime: nodejs12.x
  stage: dev

custom:
  serverless-offline:
    port: 4000

functions:
  hello:
    handler: .build/src/hello.handler
    events:
      - http: GET hello
  graphql:
    handler: .build/src/index.handler
    events:
      - http:
          method: any
          path: graphql
