service: beelzebub

provider:
  name: aws
  profile: personal
  runtime: nodejs12.x

plugins:
  - serverless-offline

custom:
  serverless-offline:
    port: 4000

functions:
  graphql:
    handler: .build/src/index.handler
    events:
      - http:
          method: any
          path: graphql
