# Generated by Django 3.0.6 on 2020-05-18 16:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('preference', '0001_initial'),
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Spelling',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spelling', models.CharField(max_length=2048)),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='preference.Language')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dictionary_spellings', to='book.Term')),
            ],
        ),
        migrations.CreateModel(
            name='Definition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=20148)),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='preference.Language')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dictionary_definitions', to='book.Term')),
            ],
        ),
    ]
