# Generated by Django 3.0.6 on 2020-05-17 19:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('book', '0001_initial'),
        ('preference', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndexTerm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('used_throughout', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Reference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('source', models.CharField(blank=True, max_length=1000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TermTermRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('sme', 'Same term'), ('sub', 'Subterm'), ('cns', 'Consider Also'), ('see', 'See'), ('sal', 'See Also')], max_length=3)),
                ('other_term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.IndexTerm')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='term_relations', to='index.IndexTerm')),
            ],
        ),
        migrations.CreateModel(
            name='TermPageRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('context', models.TextField(blank=True, null=True)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.Page')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.IndexTerm')),
            ],
        ),
        migrations.CreateModel(
            name='ReferenceTermRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('cnc', 'Concerning'), ('cns', 'Consider Also')], max_length=3)),
                ('context', models.TextField(blank=True, null=True)),
                ('page', models.ManyToManyField(blank=True, to='book.Page')),
                ('reference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.Reference')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.IndexTerm')),
            ],
        ),
        migrations.CreateModel(
            name='ReferencePageRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('ref', 'Reference'), ('and', 'And')], max_length=3)),
                ('continuation', models.CharField(blank=True, choices=[('f', 'next page'), ('ff', 'following pages'), ('in', 'inset')], max_length=2)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='references', to='book.Page')),
                ('passim', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='book.Page')),
                ('reference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.Reference')),
            ],
        ),
        migrations.AddField(
            model_name='reference',
            name='page',
            field=models.ManyToManyField(through='index.ReferencePageRelation', to='book.Page'),
        ),
        migrations.AddField(
            model_name='reference',
            name='related_term',
            field=models.ManyToManyField(blank=True, through='index.ReferenceTermRelation', to='index.IndexTerm'),
        ),
        migrations.AddField(
            model_name='reference',
            name='term',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='references', to='index.IndexTerm'),
        ),
        migrations.CreateModel(
            name='Pronunciation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField(blank=True, null=True)),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='preference.Language')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pronunciations', to='index.IndexTerm')),
            ],
        ),
        migrations.AddField(
            model_name='indexterm',
            name='page',
            field=models.ManyToManyField(blank=True, through='index.TermPageRelation', to='book.Page'),
        ),
        migrations.AddField(
            model_name='indexterm',
            name='term',
            field=models.ManyToManyField(blank=True, related_name='_indexterm_term_+', through='index.TermTermRelation', to='index.IndexTerm'),
        ),
    ]
