# Generated by Django 3.0.6 on 2020-05-12 15:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('preference', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Association',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quotation', models.TextField(blank=True, null=True)),
                ('pages', models.CharField(blank=True, max_length=2000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pronunciation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phonetic', models.CharField(blank=True, max_length=1000, null=True)),
                ('spelling', models.CharField(blank=True, max_length=1000, null=True)),
                ('sound', models.FileField(blank=True, null=True, upload_to='')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='preference.Language')),
            ],
        ),
        migrations.CreateModel(
            name='SubWord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=1000)),
                ('description', models.TextField()),
                ('language', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='preference.Language')),
            ],
        ),
        migrations.CreateModel(
            name='Term',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000)),
                ('description', models.TextField(blank=True, null=True)),
                ('in_other_languages', models.ManyToManyField(blank=True, to='index.Pronunciation')),
                ('parent_term', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children_terms', to='index.Term')),
                ('sub_words', models.ManyToManyField(blank=True, related_name='words', to='index.SubWord')),
            ],
        ),
        migrations.CreateModel(
            name='SpecialPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.IntegerField()),
                ('type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='preference.SpecialPageType')),
            ],
        ),
        migrations.CreateModel(
            name='Definition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000)),
                ('used_through_out', models.BooleanField(default=False)),
                ('association', models.ManyToManyField(blank=True, to='index.Association')),
                ('edition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='definitions', to='preference.Edition')),
                ('pronunciation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='index.Pronunciation')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='definitions', to='index.Term')),
            ],
        ),
        migrations.AddField(
            model_name='association',
            name='special_pages',
            field=models.ManyToManyField(blank=True, to='index.SpecialPage'),
        ),
        migrations.AddField(
            model_name='association',
            name='terms',
            field=models.ManyToManyField(blank=True, to='index.Term'),
        ),
        migrations.AddField(
            model_name='association',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='preference.AssociationType'),
        ),
    ]
